### ISSUE TITLE
Unable to get config in mlm pretraining

### ISSUE THREAD

**Issue by Linhvjc** [nomic-ai/contrastors#16]
I got an error:
```
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.
```
But I solved it by replacing `@root_validator` with `@root_validator(pre=True)` in `src/contrastors/config.py`

**Comment by zanussbaum** [comment]
What version of Pydantic are you running? Can you paste `pip list`?

**Comment by Linhvjc** [comment]
Oh no! My fault, I have Pydantic > 2.0.0. Thank you!

**Comment by zanussbaum** [comment]
No worries! If the requirements didn't catch this let me know and I can update :)
