### ISSUE TITLE
protobuf vision problem

### ISSUE THREAD

**Issue by cao-hy23** [nomic-ai/contrastors#18]
i have the error:
error: protobuf 4.25.3 is installed but protobuf==3.20.2 is required by {'contrastors', 'onnxconverter-common'},

but when i pip the protobuf==3.20.2 before pip onnxconverter-common,there is the new error:
error: protobuf 3.20.2 is installed but protobuf!=4.0.*,!=4.21.*,!=4.22.0,!=4.23.*,!=4.24.*,<4.26.0,>=3.20.3 is required by {'apache-beam'}

is there any solution for protobuf version conflicts？

**Comment by zanussbaum** [comment]
hey i'm also fighting this issue :( 
a quick fix is to just remove apache beam and the protobuf installations. I don't think we need apache beam here in this repo
