### ISSUE TITLE
AWS dataset issues

### ISSUE THREAD

**Issue by cao-hy23** [nomic-ai/contrastors#19]
Due to national policy reasons (China), my server cannot connect to the external network. Is there any way to download data from AWS and use it offline? What modifications need to be made to the source code?Thank you for your attention.

**Comment by zanussbaum** [comment]
During training, the dataset is stored to `/tmp`: https://github.com/nomic-ai/contrastors/blob/main/src/contrastors/dataset/torch_loader.py#L307
I think you could predownload everything to the expected location and training should work as expected: https://github.com/nomic-ai/contrastors/blob/main/src/contrastors/dataset/torch_loader.py#L311

**Comment by cao-hy23** [comment]
> During training, the dataset is stored to `/tmp`: https://github.com/nomic-ai/contrastors/blob/main/src/contrastors/dataset/torch_loader.py#L307 I think you could predownload everything to the expected location and training should work as expected: https://github.com/nomic-ai/contrastors/blob/main/src/contrastors/dataset/torch_loader.py#L311

thanks! i'll try

**Comment by zanussbaum** [comment]
Feel free to reopen if this doesn't work
