### ISSUE TITLE
unable to load local dataset for Constrastive Pretraining?

### ISSUE THREAD

**Issue by PengchengShi00** [nomic-ai/contrastors#28]
when i use the programme to load my local dataset, it comes to use the` torch_loader. StreamingShardDataset` class as its dataloader, but it can only use amazon s3fs to load, i try to modify the code to load local dataset, but meet a error: RuntimeError: Unknown layout, so i hope there could be a suitable dataloader class for loading my local dataset! Thanks!

**Comment by zanussbaum** [comment]
what kind of dataset are you trying to load? how would you load it normally? right now we only support the streaming dataset but we can support other dataset sources if they are simple enough

**Comment by PengchengShi00** [comment]
> what kind of dataset are you trying to load? how would you load it normally? right now we only support the streaming dataset but we can support other dataset sources if they are simple enough

same as your datasets, i use the .jsonl file or the .jsonl.gz file, can i make it to find the local loading dataloader class?

**Comment by zanussbaum** [comment]
yes it should be simple but the code is a bit over engineered 😅
let me think of an easy fix to this and i'll try and get something fixed for you soon

**Comment by PengchengShi00** [comment]
thanks a lot!!!

> yes it should be simple but the code is a bit over engineered 😅 let me think of an easy fix to this and i'll try and get something fixed for you soon

**Comment by zanussbaum** [comment]
this should be fixed by #29 ! You can just update your path in your data yaml's by changing it to the local path. Let me know if you run into any issues @PengchengShi00
