### ISSUE TITLE
Filtering Data For Contrastive Pretraining

### ISSUE THREAD

**Issue by daegonYu** [nomic-ai/contrastors#43]
hello. The command to run in the Filtering Data For Contrastive Pretraining section of https://github.com/nomic-ai/contrastors/tree/main/scripts/text is 

```sh
torchrun --nproc-per-node=<num_gpus> --dataset=< path_to_dataset_files_or_directory> --output_dir=<path_where_to_save_filtered_dataset> --query_key=<query_key_of_jsonl_file> --document_key=<document_of_key_jsonl_file>

```
Can I know which python file is being executed?

**Comment by zanussbaum** [comment]
ah thanks for the headsup, it should be `index_filtering.py`. I've updated the README
