### ISSUE TITLE
Running out of GPU memory on contrastive pretraining using default config

### ISSUE THREAD

**Issue by DanielMitiku** [nomic-ai/contrastors#47]
Hello,

I'm running out of memory when using contrastive pretraining using the default config. I'm using 8 GPUs with 40GB each and I ran out of memory even when I decreased the batch size to 1024.

**Comment by zanussbaum** [comment]
Can you provide which script you're running and the config?

**Comment by DanielMitiku** [comment]
I used this script:
`torchrun --nproc-per-node=8 train.py --config="configs/train/contrastive_pretrain.yaml" --dtype=bf16 `

And the config:
`train_args:
  num_epochs: 1 
  learning_rate: 2.0e-4
  weight_decay: 0.01
  warmup_steps: 700
  cooldown_steps: null
  checkpoint: null
  # wandb: true
  wandb: false
  wandb_run_name: "nomic-embed-500k-rotary-base-unsupervised"
  wandb_project_name: "text-contrastors"
  wandb_entity: "gpt4all"
  log_grads_every: 100
  log_lr_every: 10
  save_every: 2500 
  chunk_size: 64
  output_dir: "/opt/dlami/nvme/ckpts/nomic-embed-text-v1-unsupervised"
  # if using deepspeed, this will be ignored
  schedule_type: "cosine"
  max_grad_norm: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  grad_cache: true
  loss_fn: "clip"
  use_fp8: false
  clamp_logits: false
  logit_max: 100

model_args:
  logit_scale: 50
  trainable_logit_scale: false
  model_type: "encoder"
  seq_len: 2048
  pooling: "mean"
  nomic_encoder: true
  add_prefix: true
  tokenizer_name: "bert-base-uncased"
  model_name: "nomic-ai/nomic-bert-2048"
  pretrained: true
  gradient_checkpointing: false

data_args:
  input_shards: "configs/data/contrastive_pretrain.yaml"
  workers: 0 
  # batch_size: 16384
  # batch_size: 8192
  batch_size: 1024
  seed: 42
  shuffle: false
  download: true
`

**Comment by DanielMitiku** [comment]
Error logs:

<pre> base.py 410 training_step
loss = self.forward_step(inputs=batch, **model, step=step)

text_text.py 152 forward_step
loss = self._grad_cache_forward_step(model, inputs, logit_scale, **kwargs)

text_text.py 181 _grad_cache_forward_step
loss = grad_cache_loss(

loss.py 458 grad_cache_loss
accumulate_gradients(tower2, chunked_documents, chunked_document_cache, doc_rand_states)

loss.py 409 accumulate_gradients
embedding = model(**inp)["embedding"]

module.py 1532 _wrapped_call_impl
return self._call_impl(*args, **kwargs)

module.py 1541 _call_impl
return forward_call(*args, **kwargs)

distributed.py 1593 forward
else self._run_ddp_forward(*inputs, **kwargs)

distributed.py 1411 _run_ddp_forward
return self.module(*inputs, **kwargs)  # type: ignore[index]

module.py 1532 _wrapped_call_impl
return self._call_impl(*args, **kwargs)

module.py 1541 _call_impl
return forward_call(*args, **kwargs)

modeling_biencoder.py 269 forward
trunk_output = self.trunk(input_ids, attention_mask=attention_mask, **kwargs)

module.py 1532 _wrapped_call_impl
return self._call_impl(*args, **kwargs)

module.py 1541 _call_impl
return forward_call(*args, **kwargs)

modeling_nomic_bert.py 393 forward
sequence_output = self.encoder(hidden_states, attention_mask=attention_mask)

module.py 1532 _wrapped_call_impl
return self._call_impl(*args, **kwargs)

module.py 1541 _call_impl
return forward_call(*args, **kwargs)

modeling_nomic_bert.py 224 forward
hidden_states, hidden_states2, residual = layer(

module.py 1532 _wrapped_call_impl
return self._call_impl(*args, **kwargs)

module.py 1541 _call_impl
return forward_call(*args, **kwargs)

block.py 335 forward
attn_outputs = self.attn(

module.py 1532 _wrapped_call_impl
return self._call_impl(*args, **kwargs)

module.py 1541 _call_impl
return forward_call(*args, **kwargs)

attention.py 117 forward
qkv = self.rotary_emb(qkv, cu_seqlens=cu_seqlens, max_seqlen=max_seq_len, seqlen_offset=past_len)

module.py 1532 _wrapped_call_impl
return self._call_impl(*args, **kwargs)

module.py 1541 _call_impl
return forward_call(*args, **kwargs)

embedding.py 678 forward

k_rot = apply_rotary_emb_func(
-------------------------------------------------------------------------------
rotary.py 122 apply_rotary_emb

return ApplyRotaryEmb.apply(
train.py 
77 function.py <module>598 
apply
main(config, args.dtype)

train.py 57 main
trainer.train()
return super().apply(*args, **kwargs)  # type: ignore[misc]

base.py 
506 trainrotary.py 
48 forward
loss = self.training_step(
out = apply_rotary(


text_text.py 285 rotary.py training_step187 
apply_rotary
loss = super().training_step(
output = torch.empty_like(x) if not inplace else x


base.py 410 training_steptorch.cuda.OutOfMemoryError
:
CUDA out of memory. Tried to allocate 192.00 MiB. GPU 
loss = self.forward_step(inputs=batch, **model, step=step)

text_text.py 152 forward_step
loss = self._grad_cache_forward_step(model, inputs, logit_scale, **kwargs)

text_text.py 181 _grad_cache_forward_step
loss = grad_cache_loss(

loss.py 458 grad_cache_loss
accumulate_gradients(tower2, chunked_documents, chunked_document_cache, doc_rand_states)

loss.py 409 accumulate_gradients
embedding = model(**inp)["embedding"]


module.py 1532 -------------------------------------------------------------------------------_wrapped_call_impl

train.py 77 <module>
main(config, args.dtype)

train.py 57 mainreturn self._call_impl(*args, **kwargs)

trainer.train()


module.py base.py 1541 506 _call_impltrain

return forward_call(*args, **kwargs)loss = self.training_step(



distributed.py text_text.py 1593 285 forwardtraining_step

loss = super().training_step(

base.py 410 training_step
loss = self.forward_step(inputs=batch, **model, step=step)

text_text.py 152 forward_step
loss = self._grad_cache_forward_step(model, inputs, logit_scale, **kwargs)

text_text.py 181 _grad_cache_forward_step
else self._run_ddp_forward(*inputs, **kwargs)loss = grad_cache_loss(



loss.py distributed.py 458 1411 grad_cache_loss_run_ddp_forward

return self.module(*inputs, **kwargs)  # type: ignore[index]

module.py 1532 _wrapped_call_impl
return self._call_impl(*args, **kwargs)

module.py 1541 _call_impl
return forward_call(*args, **kwargs)

modeling_biencoder.py 269 forward
accumulate_gradients(tower2, chunked_documents, chunked_document_cache, doc_rand_states)

loss.py 409 accumulate_gradients
trunk_output = self.trunk(input_ids, attention_mask=attention_mask, **kwargs)
embedding = model(**inp)["embedding"]

module.py 
1532 module.py _wrapped_call_impl1532 
_wrapped_call_impl
return self._call_impl(*args, **kwargs)

module.py 1541 _call_impl
return forward_call(*args, **kwargs)

modeling_nomic_bert.py 393 forward
sequence_output = self.encoder(hidden_states, attention_mask=attention_mask)

module.py 1532 return self._call_impl(*args, **kwargs)_wrapped_call_impl


return self._call_impl(*args, **kwargs)
module.py 1541 
_call_implmodule.py 
1541 _call_impl
return forward_call(*args, **kwargs)
return forward_call(*args, **kwargs)


distributed.py 1593 modeling_nomic_bert.py forward224 
forward
hidden_states, hidden_states2, residual = layer(

module.py 1532 _wrapped_call_impl
return self._call_impl(*args, **kwargs)

module.py 1541 _call_impl
return forward_call(*args, **kwargs)

block.py 335 forward
else self._run_ddp_forward(*inputs, **kwargs)

distributed.py attn_outputs = self.attn(1411 
_run_ddp_forward

module.py return self.module(*inputs, **kwargs)  # type: ignore[index]1532 
_wrapped_call_impl

module.py return self._call_impl(*args, **kwargs)1532 
_wrapped_call_impl

return self._call_impl(*args, **kwargs)module.py 
1541 _call_impl

module.py 1541 return forward_call(*args, **kwargs)_call_impl


return forward_call(*args, **kwargs)attention.py 
117 forward

modeling_biencoder.py 269 forward
qkv = self.rotary_emb(qkv, cu_seqlens=cu_seqlens, max_seqlen=max_seq_len, seqlen_offset=past_len)

module.py trunk_output = self.trunk(input_ids, attention_mask=attention_mask, **kwargs)1532 
_wrapped_call_impl

return self._call_impl(*args, **kwargs)module.py 
1532 _wrapped_call_impl

module.py 1541 return self._call_impl(*args, **kwargs)_call_impl


return forward_call(*args, **kwargs)module.py 
1541 _call_impl

embedding.py 678 return forward_call(*args, **kwargs)forward


modeling_nomic_bert.py 393 forward
k_rot = apply_rotary_emb_func(

sequence_output = self.encoder(hidden_states, attention_mask=attention_mask)rotary.py 
122 apply_rotary_emb

module.py 1532 _wrapped_call_impl
return self._call_impl(*args, **kwargs)

module.py return ApplyRotaryEmb.apply(1541 
_call_impl

return forward_call(*args, **kwargs)function.py 
598 apply

modeling_nomic_bert.py 224 forward
hidden_states, hidden_states2, residual = layer(

module.py 1532 _wrapped_call_impl
return self._call_impl(*args, **kwargs)
return super().apply(*args, **kwargs)  # type: ignore[misc]

module.py 
1541 _call_implrotary.py 
48 forwardreturn forward_call(*args, **kwargs)


out = apply_rotary(block.py 
388 forward

rotary.py 187 apply_rotary
output = torch.empty_like(x) if not inplace else x

hidden_states = fused_add_norm_fn(torch.cuda.OutOfMemoryError
:

CUDA out of memory. Tried to allocate 192.00 MiB. GPU  has a total capacity of 39.39 GiB of which 68.31 MiB is free. Including non-PyTorch memory, this process has 39.32 GiB memory in use. Of the allocated memory 36.28 GiB is allocated by PyTorch, and 1.39 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)layer_norm.py 677 
dropout_add_layer_norm
return DropoutAddLayerNormFn.apply(

function.py 598 apply
return super().apply(*args, **kwargs)  # type: ignore[misc]

layer_norm.py 334 forward
zmat, xmat, dmask, mu, rsigma = _dropout_add_layer_norm_forward(

layer_norm.py 33 _dropout_add_layer_norm_forward
zmat, xmat, dmask, mu, rsigma = dropout_layer_norm.dropout_add_ln_fwd(

torch.cuda.OutOfMemoryError:
CUDA out of memory. Tried to allocate 190.00 MiB. GPU  has a total capacity of 39.39 GiB of which 26.31 MiB is free. Including non-PyTorch memory, this process has 39.36 GiB memory in use. Of the allocated memory 34.97 GiB is allocated by PyTorch, and 2.75 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
W0628 07:37:13.643000 140710562625344 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 55935 closing signal SIGTERM
W0628 07:37:13.644000 140710562625344 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 55936 closing signal SIGTERM
W0628 07:37:13.646000 140710562625344 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 55937 closing signal SIGTERM
W0628 07:37:13.647000 140710562625344 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 55939 closing signal SIGTERM
W0628 07:37:13.649000 140710562625344 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 55940 closing signal SIGTERM
W0628 07:37:13.651000 140710562625344 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 55941 closing signal SIGTERM
E0628 07:37:15.545000 140710562625344 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 55934) of binary: /home/ubuntu/nomic/bin/python
</pre>

**Comment by zanussbaum** [comment]
Have you tried with a smaller sequence length?

**Comment by DanielMitiku** [comment]
Decreasing chunk size seems to help. I didn't get the error till now. The chunk size will only affect speed and not performance, right? And have you trained your model with 512 sequence length? Does it affect its performance on MTEB?

**Comment by zanussbaum** [comment]
iirc we retain at 2048 and fine tune at 512
