### ISSUE TITLE
Can we continue finetune pretrained bert model on MLM task instead of doing from scratch

### ISSUE THREAD

**Issue by AndrewNgo-ini** [nomic-ai/contrastors#49]
Hello, hope you are doing well.

My goal is to extend the context length of a pretrained BERT model to 2048, and then use it for contrastive fine-tuning for text embedding.

Is it possible to extend a pretrained BERT model's context length to 2048 without starting from scratch? When I checked the project, it seemed to only load the config of the pretrained model.

Additionally, can we perform contrastive fine-tuning without doing MLM training in step 1? The config for contrastive fine-tuning is based on nomic-ai/nomic-bert-2048, so I'm not sure if it's plausible

Thank you very much.

**Comment by zanussbaum** [comment]
I've seen some people finetune an existing BERT model with absolute position embeddings to longer sequence lengths: https://x.com/andersonbcdefg/status/1794766926675349886

However, [`nomic-bert-2048`](https://huggingface.co/nomic-ai/nomic-bert-2048) already supports 2048 length context so if you want to train a model contrastively but not train a BERT model from scratch that is one option. 

Contrastive finetuning uses a model that is already trained with weakly supervised contrastive pairs: https://github.com/nomic-ai/contrastors/blob/main/src/contrastors/configs/train/contrastive_finetune.yaml#L36

However, there is some research adapting LLMs to be embedding models:
* https://arxiv.org/abs/2401.00368
* https://arxiv.org/abs/2402.09906
although this repo doesn't support those options.
