### ISSUE TITLE
Issues with loading  pretrained checkpoints for further finetuning

### ISSUE THREAD

**Issue by dipamgoswami** [nomic-ai/contrastors#51]
Hi,

Thanks for the code.
I have trained using contrastive fine-tuning and the models are saved in ckpts folder in the following way:

<img width="242" alt="Screenshot 2024-07-10 at 11 00 11" src="https://github.com/nomic-ai/contrastors/assets/40790714/4ed782dc-f970-4bae-8d8b-0c954f1f81b6">

Now, I want to load this model and further fine-tune on my dataset.

I tried setting the checkpoints argument to path "ckpts/nomic-embed-text-v1/epoch_0_model/". 
I am getting the error: 
```
FileNotFoundError:
2
No such file or directory
ckpts/nomic-embed-text-v1/epoch_0_model/rank_3_processed.json
```

If I set the model_name argument to "ckpts/nomic-embed-text-v1/epoch_0_model/". 
I get the error:
```
ValueError:
Unrecognized model in ckpts/nomic-embed-text-v1/epoch_0_model. 
Should have a `model_type` key in its config.json, or contain one of the following strings in its name: albert, align, altclip, audio-spectrogram-transformer, autoformer, bark, bart, ......
```

Can you tell me how to do that?

**Comment by DanielMitiku** [comment]
If you just want to load the model, you can pass the checkpoint argument in the model_args section. There is an error in the code though. You can fix it like this in text_text.py file. I guess this is what you need.

```
# model = BiEncoder.from_pretrained(config.pretrained, config=model_config)
 model = BiEncoder.from_pretrained(config.checkpoint, config=model_config)
```

The checkpoint args in the train_args section is to load the state and I believe that has some bugs too as the data_processed json files are not saved for some reason. But if you just want to load the model, the above will work.

**Comment by dipamgoswami** [comment]
Thanks for the suggestion! It works fine now.
