### ISSUE TITLE
Install faiss

### ISSUE THREAD

**Issue by DanielMitiku** [nomic-ai/contrastors#52]
Hello,

I'm having issue installing faiss. At this stage:
`make -C build -j faiss
`
I get this error:
make: *** build: No such file or directory.  Stop.

I am following the readme on installing faiss

**Comment by zanussbaum** [comment]
Are you in the `faiss` directory?

**Comment by DanielMitiku** [comment]
yep, downloaded faiss from the latest source code and cd into it.

**Comment by zanussbaum** [comment]
you may need to be in the `faiss` directory like here: https://github.com/facebookresearch/faiss/blob/main/faiss/CMakeLists.txt

**Comment by zanussbaum** [comment]
Hm it looks like wherever you are, there's no makefile. can you print out your `cwd` as well as `ls`?

**Comment by DanielMitiku** [comment]
pwd: 
`/opt/dlami/nvme/faiss`

ls:
`CHANGELOG.md        CONTRIBUTING.md  LICENSE    c_api             cmake-3.28.0-rc4.tar.gz  demos  tests
CMakeLists.txt      Doxyfile         README.md  cmake             conda                    faiss  tutorial
CODE_OF_CONDUCT.md  INSTALL.md       benchs     cmake-3.28.0-rc4  contrib                  misc`

**Comment by zanussbaum** [comment]
I mostly followed the instructions [here](https://github.com/facebookresearch/faiss/blob/main/INSTALL.md#step-1-invoking-cmake), did you run `cmake -B build .` in the `faiss` directory?

**Comment by DanielMitiku** [comment]
yep, everything worked until that point. I run `cmake -B build .` in the `cmake-3.28.0-rc4/` dir as the per the readme and I get this: 

`-- Configuring done (0.6s)
-- Generating done (0.2s)
-- Build files have been written to: /opt/dlami/nvme/faiss/cmake-3.28.0-rc4`

Then I changed dir into faiss after that and get that error.   I will look at the official repo if people faced similar issues.

**Comment by zanussbaum** [comment]
does it work if you cd into `/opt/dlami/nvme/faiss/cmake-3.28.0-rc4` instead?

**Comment by DanielMitiku** [comment]
No, It doesn't. `make: *** build: No such file or directory. Stop.`

**Comment by DanielMitiku** [comment]
For some reason it worked after running the cmake again in the `cmake-3.28.0-rc4` dir. I don't know what happened though. Thank you!
