### ISSUE TITLE
How to use different encoding functions for query and documents during evaluation?

### ISSUE THREAD

**Issue by dipamgoswami** [nomic-ai/contrastors#54]
Hi,

I want to use different models for encoding queries and documents during retrieval evaluation. 

In the code, I see that the same model is used in both the functions: `encode_queries` and `encode_corpus`.

line 66 and 76 in mteb_eval/eval_retrieval.py: `self.model.encode_multi_process(input_texts, self.gpu_pool, **kwargs)`

Can someone suggest how to use different models here?

**Comment by zanussbaum** [comment]
you can probably add `self.query_model` and `self.document_model` here: https://github.com/nomic-ai/contrastors/blob/main/src/contrastors/eval/encoder.py#L111 and update the `encode_queries` and `encode_corpus` accordingly
