### ISSUE TITLE
Is it possible to train the model using data stored locally? (not bucket)

### ISSUE THREAD

**Issue by upskyy** [nomic-ai/contrastors#56]
Thank you for sharing a great report.

I have one question. Is it necessary to use a cloud bucket like S3 for training? 
Is it possible to train the model using data stored locally?

**Comment by zanussbaum** [comment]
hey sorry for the delay, it's not really supported well at the moment but one hacky way is to download all your data to `/tmp/{bucket_name}/file` like here: https://github.com/nomic-ai/contrastors/blob/main/src/contrastors/dataset/text_text_loader.py#L346
