### ISSUE TITLE
Generating hard negatives for BEIR datasets

### ISSUE THREAD

**Issue by dipamgoswami** [nomic-ai/contrastors#62]
Hi,
I want to prepare the other BEIR datasets (ones having training data) for contrastive fine-tuning and thus want to mine the hard negatives. I understand that the data format is different here compared to the Hugging Face formats. I have a few questions regarding this.
1. If I am right, I need to use the `scripts/text/get_beir_negatives.py` file to do this. It is not clear to me what is expected in the argument "--beir_path". Looks like it is expecting the dataset in the original BEIR format? In that case, how is the file "shard-*.jsonl.gz" generated? Do we need to manually do this step?
2. How significant is the use of hard negatives compared to using only in-batch negatives?

**Comment by zanussbaum** [comment]
Hey
1. I downloaded the data from BEIR similar to the instructions [https://github.com/beir-cellar/beir/wiki/Datasets-available#beers-download-a-beir-dataset](https://github.com/beir-cellar/beir/wiki/Datasets-available#beers-download-a-beir-dataset). The script should [also create the ](https://github.com/nomic-ai/contrastors/blob/main/scripts/text/get_beir_negatives.py#L189-L191)`shard-*.jsonl.gz` files
2. For fine-tuning, we found it to be very important. I don't have any hard numbers per se, but mining the negatives helped a ton for retrieval vs. just using the BEIR datasets with a large batch size with in-batch negatives
