### ISSUE TITLE
mlm pretrain error

### ISSUE THREAD

**Issue by charliedream1** [nomic-ai/contrastors#65]
I'm using mlm pretraining. I found memory occupation is not even, some gpu memory is very high, even several times large than the others. Some gpu is free and waiting for one gpu to complete a batch sometime. Overall, GPU utilization is very low. And during training, I got error as below. 

RuntimeError:
CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I got questions as below:
1. how to improve GPU utilization to increase efficiency? 
2. How to solve the CUDA error? When I train LLM with other training framework, there's no this error

**Comment by zanussbaum** [comment]
This usually happens when you run out of memory. you can try to use gradient accumulation or a smaller batch size

**Comment by keyuchen21** [comment]
@charliedream1  @zanussbaum any updates?
