### ISSUE TITLE
Adaptation for Computer Vision

### ISSUE THREAD

**Issue by VTrivedy** [nomic-ai/contrastors#8]
Awesome work y'all!  Any examples or models for computer vision use-cases with Matryoshka + Contrastive Loss?  For example, how easy is it to swap out the BERT with VIT/DINO from huggingface models hub?

**Comment by zanussbaum** [comment]
I haven't trained any image contrastive models with matryoshka but should be technically feasible if you swap in the models although I don't know of any image-only contrastive models. Look for this to be updated in the future :D
